@extends('common.master')

@section('content')


    <h2>DNS Record: {{$record->hostname}}.{{ $record->dnszone->domain }}</h2>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item"><a href="{{url("/dns-records/")}}">DNS Records</a></li>
        <li class="breadcrumb-item active">{{$record->hostname}}.{{ $record->dnszone->domain }}</li>
    </ol>
    <div>

        <!-- Nav tabs -->
        <ul class="nav nav-tabs" role="tablist">
            <li role="presentation" class="active"><a href="#ipInfo" aria-controls="ipInfo" role="tab" data-toggle="tab">DNS Record Info</a></li>
        </ul>

        <!-- Tab panes -->
        <div class="tab-content">
            <div role="tabpanel" class="tab-pane active" id="ipInfo">

                <Table class="table table-responsive table-condensed table-striped table-bordered">
                    <tr>
                        <th>Hostname</th>
                        <td>{{$record->hostname}}</td>
                    </tr>
                    <tr>
                        <th>Domain</th>
                        <td>{{$record->dnszone->domain}}</td>
                    </tr>
                    <tr>
                        <th>Target</th>
                        <td>{{$record->target}}</td>
                    </tr>
                    <tr>
                        <th>TTL</th>
                        <td>{{$record->ttl}}</td>
                    </tr>
                    <tr>
                        <th>Record Type</th>
                        <td>{{$record->record_type}}</td>
                    </tr>
                    <tr>
                        <th>Zone</th>
                        <td><a href="/dns-zones/{{ $record->dnszone->id }}">{{$record->dnszone->name}}</a> ({{$record->dnszone->domain}})</td>
                    </tr>
                    <tr>
                        <th>Associated IP Record</th>
                        <td>
                            @if( $record->ip )
                            <a href="/ip/{{ $record->ip->id }}">{{$record->ip->name}}</a></td>
                            @else
                            @if( $record->dhcpLease )
                            DHCP
                            @else
                            none
                            @endif
                            @endif
                    </tr>

                    <tr>
                        <th>Created</th>
                        <td>{{$record->created_at}}</td>
                    </tr>
                    <tr>
                        <th>Updated</th>
                        <td>{{$record->updated_at}}</td>
                    </tr>
                </table>

                <form method="POST" action="{{ url("/ips/" . $record->id . "") }}" accept-charset="UTF-8">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}">
                    <input type="hidden" name="_method" value="DELETE"/>
                    @if ($record->ips_id)
                        <div class="alert alert-warning" role="alert">
                            This record cannot be edited or deleted because it is linked to and IP Address record. To make changes to this record update the IP Address record.
                        </div>
                    @endif
                    @if ($record->dhcp_lease_id)
                        <div class="alert alert-warning" role="alert">
                            This record cannot be edited because it was generated by a DHCP lease.
                        </div>
                    @endif
                    @if ( ($record->ips_id == "") && ($record->dhcp_lease_id == "") )
                        <a href="{{ url("/dns-records/" . $record->id . "/edit") }}">
                        <button type="button" class="btn btn-sm btn-success">Edit DNS Record</button>
                    </a>
                    @endif
                    @if ( $record->ips_id == "" )
                    <button type="button" class="btn btn-sm btn-danger">Delete DNS Record</button>
                    @endif

                </form>
            </div>

        </div>

    </div>

@endsection

